# Deploy to DockerHub
name: Deploy to DockerHub

on:
  push:
    branches: [ 'main' ]
  pull_request: [ 'main' ]

  jobs:

    deploy:

      runs-on: self-hosted

      steps:
        - uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/flappybird:latest, ${{ secrets.DOCKER_USERNAME }}/flappybird:${{ github.sha }}